export const SHOW_SIDEBAR = "SHOW_SIDEBAR"
export const HIDDEN_SIDEBAR = "HIDDEN_SIDEBAR"

export const SHOW_MODAL_ADD = "SHOW_MODAL_ADD"
export const HIDDEN_MODAL_ADD = "HIDDEN_MODAL_ADD"

export const SHOW_MODAL_EDIT = "SHOW_MODAL_EDIT"
export const HIDDEN_MODAL_EDIT = "HIDDEN_MODAL_EDIT"