export const GET_NOTES = "GET_NOTES"
export const GET_NOTES_OK = "GET_NOTES_OK"
export const GET_NOTES_ERROR = "GET_NOTES_ERROR"

export const CREATE_NOTE = "CREATE_NOTE"
export const CREATE_NOTE_OK = "CREATE_NOTE_OK"
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR"

export const TOGGLE_FEATURED = "TOGGLE_FEATURED"
export const TOGGLE_ARCHIVED = "TOGGLE_FEATURED"

export const DELETE_NOTE = "DELETE_NOTE"
export const DELETE_NOTE_OK = "DELETE_NOTE_OK"
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR"

export const LOAD_NOTE_TO_EDIT = "LOAD_NOTE_TO_EDIT"
export const UPDATE_NOTE_LOADING = "DELETE_NOTE_OK"
export const UPDATE_NOTE_ERROR = "DELETE_NOTE_ERROR"
export const UPDATE_NOTE = "UPDATE_NOTE"
